/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cfms.kafka;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class InventoryProduct extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7847562435625050279L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InventoryProduct\",\"namespace\":\"com.cfms.kafka\",\"fields\":[{\"name\":\"productName\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InventoryProduct> ENCODER =
      new BinaryMessageEncoder<InventoryProduct>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InventoryProduct> DECODER =
      new BinaryMessageDecoder<InventoryProduct>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<InventoryProduct> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<InventoryProduct> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<InventoryProduct>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this InventoryProduct to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a InventoryProduct from a ByteBuffer. */
  public static InventoryProduct fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence productName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InventoryProduct() {}

  /**
   * All-args constructor.
   * @param productName The new value for productName
   */
  public InventoryProduct(java.lang.CharSequence productName) {
    this.productName = productName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'productName' field.
   * @return The value of the 'productName' field.
   */
  public java.lang.CharSequence getProductName() {
    return productName;
  }

  /**
   * Sets the value of the 'productName' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.CharSequence value) {
    this.productName = value;
  }

  /**
   * Creates a new InventoryProduct RecordBuilder.
   * @return A new InventoryProduct RecordBuilder
   */
  public static com.cfms.kafka.InventoryProduct.Builder newBuilder() {
    return new com.cfms.kafka.InventoryProduct.Builder();
  }

  /**
   * Creates a new InventoryProduct RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InventoryProduct RecordBuilder
   */
  public static com.cfms.kafka.InventoryProduct.Builder newBuilder(com.cfms.kafka.InventoryProduct.Builder other) {
    return new com.cfms.kafka.InventoryProduct.Builder(other);
  }

  /**
   * Creates a new InventoryProduct RecordBuilder by copying an existing InventoryProduct instance.
   * @param other The existing instance to copy.
   * @return A new InventoryProduct RecordBuilder
   */
  public static com.cfms.kafka.InventoryProduct.Builder newBuilder(com.cfms.kafka.InventoryProduct other) {
    return new com.cfms.kafka.InventoryProduct.Builder(other);
  }

  /**
   * RecordBuilder for InventoryProduct instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InventoryProduct>
    implements org.apache.avro.data.RecordBuilder<InventoryProduct> {

    private java.lang.CharSequence productName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cfms.kafka.InventoryProduct.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productName)) {
        this.productName = data().deepCopy(fields()[0].schema(), other.productName);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing InventoryProduct instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cfms.kafka.InventoryProduct other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.productName)) {
        this.productName = data().deepCopy(fields()[0].schema(), other.productName);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'productName' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductName() {
      return productName;
    }

    /**
      * Sets the value of the 'productName' field.
      * @param value The value of 'productName'.
      * @return This builder.
      */
    public com.cfms.kafka.InventoryProduct.Builder setProductName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.productName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'productName' field has been set.
      * @return True if the 'productName' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'productName' field.
      * @return This builder.
      */
    public com.cfms.kafka.InventoryProduct.Builder clearProductName() {
      productName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InventoryProduct build() {
      try {
        InventoryProduct record = new InventoryProduct();
        record.productName = fieldSetFlags()[0] ? this.productName : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InventoryProduct>
    WRITER$ = (org.apache.avro.io.DatumWriter<InventoryProduct>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InventoryProduct>
    READER$ = (org.apache.avro.io.DatumReader<InventoryProduct>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
